{ pkgs, ... }:

let
  awesomeVim = pkgs.fetchFromGitHub {
    owner = "amix";
    repo = "vimrc";
    rev = "46294d589d15d2e7308cf76c58f2df49bbec31e8";
    sha256 = "1j17lv5r61r825dhv1n69glmq7glm6qs483g8sxlv50rd2jsjml3";
  };
in
{
  # Use standard Vim, not Neovim. Awesome Vim is installed declaratively below
  # instead of running the upstream curl/git installer against $HOME.
  programs.vim = {
    enable = true;
    defaultEditor = true;
  };

  home.sessionVariables = {
    EDITOR = "vim";
    VISUAL = "vim";
  };

  home.packages = with pkgs; [
    # Useful with the bundled Awesome Vim plugins and syntax tooling.
    ctags
  ];

  # Declarative equivalent of:
  #   git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
  #   sh ~/.vim_runtime/install_awesome_vimrc.sh
  # Keep mutable temp/plugin-customization directories in $HOME while symlinking
  # the pinned upstream runtime from the Nix store.
  home.file.".vim_runtime/autoload".source = "${awesomeVim}/autoload";
  home.file.".vim_runtime/sources_forked".source = "${awesomeVim}/sources_forked";
  home.file.".vim_runtime/sources_non_forked".source = "${awesomeVim}/sources_non_forked";
  home.file.".vim_runtime/vimrcs".source = "${awesomeVim}/vimrcs";
  home.file.".vim_runtime/install_awesome_vimrc.sh" = {
    source = "${awesomeVim}/install_awesome_vimrc.sh";
    executable = true;
  };
  home.file.".vim_runtime/update_plugins.py".source = "${awesomeVim}/update_plugins.py";
  home.file.".vim_runtime/my_configs.vim".text = ''
    " Managed by Home Manager via ~/.config/nix-darwin/home/editor.nix
    " Put Awesome Vim customizations here declaratively.
  '';
  home.file.".vim_runtime/my_plugins/.keep".text = "";
  home.file.".vim_runtime/temp_dirs/undodir/.keep".text = "";

  home.file.".vimrc".text = ''
    " DO NOT EDIT THIS FILE
    " Managed by Home Manager via ~/.config/nix-darwin/home/editor.nix
    " Add customizations declaratively in .vim_runtime/my_configs.vim above.

    set runtimepath+=~/.vim_runtime

    source ~/.vim_runtime/vimrcs/basic.vim
    source ~/.vim_runtime/vimrcs/filetypes.vim
    source ~/.vim_runtime/vimrcs/plugins_config.vim
    source ~/.vim_runtime/vimrcs/extended.vim
    try
      source ~/.vim_runtime/my_configs.vim
    catch
    endtry
  '';
}
